FROM nodered/node-red-docker

USER node-red
#COPY --chown=node-red:node-red settings.js /data/.
#COPY --chown=node-red:node-red flows.json /data/.
#COPY --chown=node-red:node-red flows_cred.json /data/.
